name: flutter_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7 
  grouped_list: ^6.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2 
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  image_picker: ^1.0.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  




flutter:

  
  uses-material-design: true
  assets:
  - assets/images/
 


  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
